# CLASSIFICATION

### LOGISTIC REGRESSION

1. for one use cases / independent variable (ex- age):-
     ln p/(1-p) = h0 + h2X1

2. for multiple use cases / independent variables (ex- age, income, education, family or single):-
    ln p/(1-p) = h0 + h2X1 +h2X2 + h3X3 + h4X4

Logistic Regression plot graph based on probabilities between EX:- NO(0) OR YES(1) (used in most of the cases of binary outcome)
  

BEST CURVE<= MAX LIKELIHOOD

In [48]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [49]:
dataset=pd.read_csv("Social_Network_Ads.csv")
X=dataset.iloc[:,:-1].values 
y=dataset.iloc[:,-1]

In [50]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [51]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [53]:
X_train

array([[    44,  39000],
       [    32, 120000],
       [    38,  50000],
       [    32, 135000],
       [    52,  21000],
       [    53, 104000],
       [    39,  42000],
       [    38,  61000],
       [    36,  50000],
       [    36,  63000],
       [    35,  25000],
       [    35,  50000],
       [    42,  73000],
       [    47,  49000],
       [    59,  29000],
       [    49,  65000],
       [    45, 131000],
       [    31,  89000],
       [    46,  82000],
       [    47,  51000],
       [    26,  15000],
       [    60, 102000],
       [    38, 112000],
       [    40, 107000],
       [    42,  53000],
       [    35,  59000],
       [    48,  41000],
       [    48, 134000],
       [    38, 113000],
       [    29, 148000],
       [    26,  15000],
       [    60,  42000],
       [    24,  19000],
       [    42, 149000],
       [    46,  96000],
       [    28,  59000],
       [    39,  96000],
       [    28,  89000],
       [    41,  72000],
       [    45,  26000],


In [54]:
X_test

array([[    30,  87000],
       [    38,  50000],
       [    35,  75000],
       [    30,  79000],
       [    35,  50000],
       [    27,  20000],
       [    31,  15000],
       [    36, 144000],
       [    18,  68000],
       [    47,  43000],
       [    30,  49000],
       [    28,  55000],
       [    37,  55000],
       [    39,  77000],
       [    20,  86000],
       [    32, 117000],
       [    37,  77000],
       [    19,  85000],
       [    55, 130000],
       [    35,  22000],
       [    35,  47000],
       [    47, 144000],
       [    41,  51000],
       [    47, 105000],
       [    23,  28000],
       [    49, 141000],
       [    28,  87000],
       [    29,  80000],
       [    37,  62000],
       [    32,  86000],
       [    21,  88000],
       [    37,  79000],
       [    57,  60000],
       [    37,  53000],
       [    24,  58000],
       [    18,  52000],
       [    22,  81000],
       [    34,  43000],
       [    31,  34000],
       [    49,  36000],


In [55]:
y_train

250    0
63     1
312    0
159    1
283    1
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 300, dtype: int64

In [66]:
y_test=np.array(y_test)


Feature Scaling

In [57]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [58]:
X_train

array([[ 0.58, -0.89],
       [-0.61,  1.46],
       [-0.01, -0.57],
       [-0.61,  1.9 ],
       [ 1.37, -1.41],
       [ 1.47,  1.  ],
       [ 0.09, -0.8 ],
       [-0.01, -0.25],
       [-0.21, -0.57],
       [-0.21, -0.19],
       [-0.31, -1.29],
       [-0.31, -0.57],
       [ 0.38,  0.1 ],
       [ 0.88, -0.6 ],
       [ 2.07, -1.18],
       [ 1.08, -0.13],
       [ 0.68,  1.78],
       [-0.71,  0.56],
       [ 0.78,  0.36],
       [ 0.88, -0.54],
       [-1.2 , -1.58],
       [ 2.17,  0.94],
       [-0.01,  1.23],
       [ 0.19,  1.08],
       [ 0.38, -0.48],
       [-0.31, -0.31],
       [ 0.98, -0.83],
       [ 0.98,  1.87],
       [-0.01,  1.26],
       [-0.9 ,  2.27],
       [-1.2 , -1.58],
       [ 2.17, -0.8 ],
       [-1.4 , -1.47],
       [ 0.38,  2.3 ],
       [ 0.78,  0.77],
       [-1.  , -0.31],
       [ 0.09,  0.77],
       [-1.  ,  0.56],
       [ 0.28,  0.07],
       [ 0.68, -1.26],
       [-0.51, -0.02],
       [-1.8 ,  0.36],
       [-0.71,  0.13],
       [ 0.

In [59]:
X_test

array([[-0.8 ,  0.5 ],
       [-0.01, -0.57],
       [-0.31,  0.16],
       [-0.8 ,  0.27],
       [-0.31, -0.57],
       [-1.1 , -1.44],
       [-0.71, -1.58],
       [-0.21,  2.16],
       [-1.99, -0.05],
       [ 0.88, -0.77],
       [-0.8 , -0.6 ],
       [-1.  , -0.42],
       [-0.11, -0.42],
       [ 0.09,  0.22],
       [-1.8 ,  0.48],
       [-0.61,  1.37],
       [-0.11,  0.22],
       [-1.89,  0.45],
       [ 1.67,  1.75],
       [-0.31, -1.38],
       [-0.31, -0.65],
       [ 0.88,  2.16],
       [ 0.28, -0.54],
       [ 0.88,  1.03],
       [-1.5 , -1.21],
       [ 1.08,  2.07],
       [-1.  ,  0.5 ],
       [-0.9 ,  0.3 ],
       [-0.11, -0.22],
       [-0.61,  0.48],
       [-1.7 ,  0.53],
       [-0.11,  0.27],
       [ 1.87, -0.28],
       [-0.11, -0.48],
       [-1.4 , -0.34],
       [-1.99, -0.51],
       [-1.6 ,  0.33],
       [-0.41, -0.77],
       [-0.71, -1.03],
       [ 1.08, -0.97],
       [-1.1 ,  0.53],
       [ 0.28, -0.51],
       [-1.1 ,  0.42],
       [-0.

Training Logistic Regression on Training Set

In [60]:
from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

Predicting New Result

In [68]:
classifier.predict(sc.transform([[30,87000]]))

array([0], dtype=int64)

In [69]:
y_pred=classifier.predict(X_test)


print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [74]:
classifier.score(X_test,y_test)

0.89

In [77]:
#Accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')


Accuracy: 0.89


The previous method using classifier.score(y_pred.reshape(1,-1),y_test.reshape(1,-1)) didn't work because the score method in scikit-learn is designed to evaluate the model's performance on input features (X) and corresponding labels (y)

Why We Use accuracy_score:
accuracy_score(y_test, y_pred): This function directly compares the predicted labels (y_pred) with the actual labels (y_test) to compute accuracy. It doesn't require the original feature data (X_test) because it works with the predictions already made.

MAKING THE CONFUSION MATRIX

         +ve     -ve
        -------------
 +ve    | TP  |  FP  |      TP ---> 1    1
        --------------
 -ve    | FN  | TN   |      TN----> 1    0
        --------------      FP----> 0    0
        confusion matrix    FN----> 0    1

In [78]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[65,  3],
       [ 8, 24]], dtype=int64)

In [79]:
#Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.89

Visualising the Training set Results