# DATA PRE- PROCESSING TOOLS


In [16]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [17]:
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [18]:
X= dataset.iloc[:, :-1].values              #lowerbound : upper bound
X                                         #include : exclude
                                            #  0     :  -1    -> all except the last column

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [66]:
# Y= dataset[["Age",'Salary']]

In [68]:
Y=dataset.iloc[:,-1:].values        #Choose last coloumn only + choose all rows
Y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

TAKING CARE OF THE MISSING DATA


In [20]:
# delete the data (pandas) or replace missing values with the average/mean of all data (sklearn)

from sklearn.impute import SimpleImputer     #from sklearn lib inside impute module create class SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])                 #exclude string coloumns  #fit store value as a matrix
X[:,1:3]=imputer.transform(X[:,1:3])  #transform change null value to desired value

In [21]:
X      #nan is replaced by the mean value

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding categorical data

encoding categorical data into numerical

1. Encoding Independent Variable

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [23]:
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [24]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [29]:
X.shape

(10, 5)

2. Encoding Dependent Variable

In [25]:
from sklearn.preprocessing import LabelEncoder

In [62]:
le= LabelEncoder()
Y=np.array(le.fit_transform(Y))
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [63]:
#test ---------------------------------------------------------------
Y.shape

(10,)

In [52]:
CT=ColumnTransformer(transformers=[('encoder', LabelEncoder(), Y[0:])], remainder='passthrough')

# The ColumnTransformer is designed to apply different transformers to different columns of a DataFrame. 
# However, LabelEncoder is not intended to be used within a ColumnTransformer for this purpose. 
# Instead, LabelEncoder is typically used directly on an array.


for selecting object datatype or categorical values--> df.select_dtypes(include='O')
for numerical type --> df.select_dtypes(exclude='O)

# Splitting dataset into training set and test set

In [69]:
from sklearn.model_selection import train_test_split

#recommened 80% for training data & 20% test data i.e test_size=0.2

X_train, X_test, Y_train , Y_test = train_test_split(X, Y , test_size=0.2,random_state=1)

In [70]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [71]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [72]:
Y_train

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [73]:
Y_test

array([['No'],
       ['Yes']], dtype=object)

# Feature Scaling

all features into same scale

1. Standardistion -> works all the time
2. Normalisation -> only works when distribution is normal

Standardisation:-  Xstand = x- mean(x) /
                           
                           standard deviation
    
Normalisation:- Xnorm= x- min(x) / 
                     
                      max(x)-min(x)

In [76]:
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()


In [77]:
# we only apply feature scaling on columns needed it and not on one hot code values we updated

X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [78]:
X_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

In [79]:
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)

Why We Need Feature Scaling?

1. Equal Contribution of Features: In many machine learning algorithms, the scale of features affects how the model learns from the data. If features have vastly different scales, those with larger scales will dominate, and the model may become biased towards them.

2. Improved Convergence in Gradient Descent: Algorithms like linear regression and neural networks use gradient descent to minimize the error. If features are not scaled, the optimization process can be inefficient and slow, as the steps taken in each direction (for each feature) can vary significantly.

3. Distance-Based Algorithms: Algorithms like k-Nearest Neighbors (k-NN) and k-means clustering rely on distance calculations. If one feature has a much larger range than others, it will disproportionately affect the distance, skewing the results.